In [1]:
import numpy as np
import os
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd

# P1 data
data1_path = '../Datasets/TaxiBJ_main/TAXIBJ2013.grid'

# load P1 data
xdata1 = pd.read_csv(data1_path)
xdata1

dyna_id   type                  time  row_id  column_id  inflow  \
0              0  state  2013-07-01T00:00:00Z       0        0.0     0.0   
1              1  state  2013-07-01T00:30:00Z       0        0.0     0.0   
2              2  state  2013-07-01T01:00:00Z       0        0.0     0.0   
3              3  state  2013-07-01T01:30:00Z       0        0.0     0.0   
4              4  state  2013-07-01T02:00:00Z       0        0.0     0.0   
...          ...    ...                   ...     ...        ...     ...   
4964347  4964347  state  2013-10-29T21:30:00Z      31       31.0     8.0   
4964348  4964348  state  2013-10-29T22:00:00Z      31       31.0     9.0   
4964349  4964349  state  2013-10-29T22:30:00Z      31       31.0    10.0   
4964350  4964350  state  2013-10-29T23:00:00Z      31       31.0     6.0   
4964351  4964351  state  2013-10-29T23:30:00Z      31       31.0     8.0   

         outflow  
0            0.0  
1            0.0  
2            0.0  
3            0.0  
4            0.0  
...          ...  
4964347      7.0  
4964348      7.0  
4964349     10.0  
4964350      6.0  
4964351      9.0  

[4964352 rows x 7 columns]

In [2]:
xdata1 = xdata1.drop(columns=['dyna_id', 'type'])
xdata1_gb = xdata1.groupby('time')#.apply(print)
# number of groups
xdata1_gb.ngroups

# convert to list
xdata1_gb = list(xdata1_gb)
xdata1_gb[0]
# remove first group since it is not right
xdata1_gb = xdata1_gb[1:]
len(xdata1_gb)

4849

('\t1',
         time  row_id  column_id  inflow  outflow
 4964268  \t1      31        1.0     3.0      NaN)

4848

In [3]:
# nth data (nth, 2, 32, 32)
n = 0
# xdata1_gb[n][0] is the specific 30 minute interval time
data = xdata1_gb[n][1] # the associated dataframe
data_inflow = data.pivot_table(values='inflow', index='row_id', columns='column_id').to_numpy()
data_outflow = data.pivot_table(values='outflow', index='row_id', columns='column_id').to_numpy()

data_inflow
data_outflow

array([[  0.,  20.,  41., ...,   7.,   1.,  40.],
       [  0.,  11.,   8., ...,  22.,   7.,  96.],
       [  0.,   9.,   5., ...,  14., 198., 117.],
       ...,
       [  1.,   3.,   4., ...,   8.,   6.,   3.],
       [  0.,   0.,   0., ...,   9.,   0.,   7.],
       [  1.,   0.,   0., ...,  17.,  20.,   7.]])

array([[  0.,  21.,  44., ...,   6.,   1.,  38.],
       [  0.,  11.,   8., ...,  23.,   6.,  93.],
       [  0.,   9.,   5., ...,  15., 201., 120.],
       ...,
       [  2.,   3.,   4., ...,   7.,   7.,   3.],
       [  0.,   0.,   0., ...,   9.,   0.,   7.],
       [  1.,   0.,   0., ...,  19.,  21.,   8.]])

In [4]:
# a single array containing nth data (nth, 2, 32, 32)
data_output = np.array([[data_inflow, data_outflow]])
data_output.shape

(1, 2, 32, 32)

In [5]:
# convert data to numpy array
size = len(xdata1_gb)
entire_data = np.empty([size, 2, 32, 32])
for i in range(size):
    data = xdata1_gb[i][1]
    data_inflow = data.pivot_table(values='inflow', index='row_id', columns='column_id').to_numpy()
    data_outflow = data.pivot_table(values='outflow', index='row_id', columns='column_id').to_numpy()
    entire_data[i, 0] = data_inflow
    entire_data[i, 1] = data_outflow

In [6]:
entire_data[4847]

array([[[  0.,  13.,  23., ...,   8.,   2.,  28.],
        [  0.,  19.,  11., ...,  21.,   9.,  78.],
        [  0.,   9.,  11., ...,  10., 248., 172.],
        ...,
        [  3.,   4.,   6., ...,  11.,   9.,   3.],
        [  1.,   0.,   0., ...,  11.,   0.,  10.],
        [  1.,   1.,   0., ...,  14.,  21.,   8.]],

       [[  0.,  13.,  27., ...,   8.,   2.,  27.],
        [  0.,  18.,  12., ...,  22.,   8.,  81.],
        [  0.,   9.,  10., ...,  10., 239., 167.],
        ...,
        [  2.,   4.,   6., ...,  11.,   9.,   3.],
        [  1.,   0.,   0., ...,  11.,   0.,   8.],
        [  1.,   1.,   0., ...,  15.,  21.,   9.]]])